# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: election.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lection.proto\x12\x08\x65lection\"8\n\x0f\x45lectionRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\"\x1e\n\x10\x45lectionResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\'\n\x12LeaderAnnouncement\x12\x11\n\tleader_id\x18\x01 \x01(\t\"\'\n\x10HeartbeatRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd0\x01\n\x0f\x45lectionService\x12\x46\n\rStartElection\x12\x19.election.ElectionRequest\x1a\x1a.election.ElectionResponse\x12=\n\x0e\x41nnounceLeader\x12\x1c.election.LeaderAnnouncement\x1a\r.election.Ack\x12\x36\n\tHeartbeat\x12\x1a.election.HeartbeatRequest\x1a\r.election.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ELECTIONREQUEST']._serialized_start=28
  _globals['_ELECTIONREQUEST']._serialized_end=84
  _globals['_ELECTIONRESPONSE']._serialized_start=86
  _globals['_ELECTIONRESPONSE']._serialized_end=116
  _globals['_LEADERANNOUNCEMENT']._serialized_start=118
  _globals['_LEADERANNOUNCEMENT']._serialized_end=157
  _globals['_HEARTBEATREQUEST']._serialized_start=159
  _globals['_HEARTBEATREQUEST']._serialized_end=198
  _globals['_ACK']._serialized_start=200
  _globals['_ACK']._serialized_end=222
  _globals['_ELECTIONSERVICE']._serialized_start=225
  _globals['_ELECTIONSERVICE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
