# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"\xa2\x02\n\x12TransactionRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x39\n\x0b\x63redit_card\x18\x04 \x01(\x0b\x32$.transaction_verification.CreditCard\x12\x15\n\rdiscount_code\x18\x05 \x01(\t\x12\x41\n\x0f\x62illing_address\x18\x06 \x01(\x0b\x32(.transaction_verification.BillingAddress\x12\x17\n\x0fshipping_method\x18\x07 \x01(\t\x12\x14\n\x0cuser_comment\x18\x08 \x01(\t\x12\x15\n\rgift_wrapping\x18\t \x01(\x08\"B\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"v\n\x13TransactionResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12=\n\x07\x64\x65tails\x18\x03 \x01(\x0b\x32,.transaction_verification.TransactionDetails\"\xee\x01\n\x12TransactionDetails\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x41\n\x0f\x62illing_address\x18\x03 \x01(\x0b\x32(.transaction_verification.BillingAddress\x12\x15\n\rdiscount_code\x18\x04 \x01(\t\x12\x16\n\x0e\x63harged_amount\x18\x05 \x01(\x02\x12\x17\n\x0fshipping_method\x18\x06 \x01(\t\x12\x14\n\x0cuser_comment\x18\x07 \x01(\t\x12\x15\n\rgift_wrapping\x18\x08 \x01(\x08\x32\x8b\x01\n\x17TransactionVerification\x12p\n\x11VerifyTransaction\x12,.transaction_verification.TransactionRequest\x1a-.transaction_verification.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=61
  _globals['_TRANSACTIONREQUEST']._serialized_end=351
  _globals['_CREDITCARD']._serialized_start=353
  _globals['_CREDITCARD']._serialized_end=419
  _globals['_BILLINGADDRESS']._serialized_start=421
  _globals['_BILLINGADDRESS']._serialized_end=512
  _globals['_TRANSACTIONRESPONSE']._serialized_start=514
  _globals['_TRANSACTIONRESPONSE']._serialized_end=632
  _globals['_TRANSACTIONDETAILS']._serialized_start=635
  _globals['_TRANSACTIONDETAILS']._serialized_end=873
  _globals['_TRANSACTIONVERIFICATION']._serialized_start=876
  _globals['_TRANSACTIONVERIFICATION']._serialized_end=1015
# @@protoc_insertion_point(module_scope)
