# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x0eorder_executor\"\x10\n\x0e\x45xecuteRequest\"E\n\x0f\x45xecuteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\"\'\n\x10\x45xitNotification\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"\x1b\n\x07\x45xitAck\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\xad\x01\n\rOrderExecutor\x12S\n\x10\x45xecuteNextOrder\x12\x1e.order_executor.ExecuteRequest\x1a\x1f.order_executor.ExecuteResponse\x12G\n\nNotifyExit\x12 .order_executor.ExitNotification\x1a\x17.order_executor.ExitAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTEREQUEST']._serialized_start=40
  _globals['_EXECUTEREQUEST']._serialized_end=56
  _globals['_EXECUTERESPONSE']._serialized_start=58
  _globals['_EXECUTERESPONSE']._serialized_end=127
  _globals['_EXITNOTIFICATION']._serialized_start=129
  _globals['_EXITNOTIFICATION']._serialized_end=168
  _globals['_EXITACK']._serialized_start=170
  _globals['_EXITACK']._serialized_end=197
  _globals['_ORDEREXECUTOR']._serialized_start=200
  _globals['_ORDEREXECUTOR']._serialized_end=373
# @@protoc_insertion_point(module_scope)
